name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild -scheme Strada -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4'
#       run: swift build -v
    - name: Run tests
      run: xcodebuild test -project Strada.xcodeproj -scheme Strada -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.4'
#       run: swift test -v
